name: Continuous Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      api_base_url:
        description: 'API Base URL'
        required: false
        type: string

jobs:
  cont-integration:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build-with-prod-api:
    name: Build APK
    runs-on: ubuntu-latest
    needs: cont-integration
    env:
      API_URL: ${{ github.event.inputs.api_base_url || secrets.API_BASE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk \
            --dart-define=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
            --dart-define=API_BASE_URL=${{ env.API_URL }}

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.run_number }}
          path: build/app/outputs/apk/release/app-release.apk

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-with-prod-api
    permissions:
      contents: write
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk-${{ github.run_number }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            🚀 **Release v${{ github.run_number }}**
            
            **Trigger:** ${{ github.event_name == 'push' && '🤖 Automatic (Push)' || '👤 Manual' }}
            **Built by:** @${{ github.actor }}
            **Build Date:** 2025-01-16 17:11:55 UTC
            
            **Build Information:**
            - Branch: `${{ github.ref_name }}`
            - Commit: [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            
            **Downloads:**
            - [📱 Android APK](./app-release.apk)
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
