name: Continuous Delivery
on:
  push:
    branches:
      - master

jobs:
  cont-integration:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: cont-integration
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - run: flutter pub get

      - run: flutter build apk --dart-define=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }}

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # Add this line to grant write permissions to the contents
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk
  
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: app-release.apk 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
