name: Continuous Integration

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
  workflow_call:

jobs:
  perform-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  integration-tests:
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  code-quality-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}