name: Continuous Delivery
on:
  push:
    branches:
      - release

jobs:
  cont-integration:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build-with-qa-api:
    name: Build APK
    runs-on: ubuntu-latest
    needs: cont-integration
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk \
            --dart-define=GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} 

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: delivery-apk-${{ github.run_number }}
          path: build/app/outputs/apk/release/app-release.apk