name: Functional Tests

on:
  push:
    branches:
      - release
  repository_dispatch:
    types: [backend-updated]
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: ghcr.io/fcuya13/elimapass-spring:latest
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl --fail http://localhost:8080/actuator/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elimapass
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpass
          SPRING_PROFILES_ACTIVE: ci

      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: elimapass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart functional tests
        run: flutter test test/functional_test