name: Functional Tests

on:
  push:
    branches:
      - release
  repository_dispatch:
    types: [backend-updated]
  workflow_call:

  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start services
        run: |
          echo "Starting PostgreSQL..."
          docker compose -f docker-compose.test.yml up -d postgres
          
          sleep 5         
          
          echo "Waiting for PostgreSQL to be healthy..."
          docker compose -f docker-compose.test.yml up -d backend
          
          sleep 5

      - name: Verify services are running
        run: |
          echo "Service status:"
          docker-compose -f docker-compose.test.yml ps
          
          echo "Testing PostgreSQL connection:"
          docker-compose -f docker-compose.test.yml exec -T postgres pg_isready -U postgres
          
          echo "Testing backend health:"
          curl -f http://localhost:8080/actuator/health

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart functional tests
        run: flutter test test/functional_test  --dart-define=BACKEND_URL=http://localhost:8080/

      - name: Cleanup
        if: always()
        run: docker stop backend || true