name: Validate and Test
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened]
  workflow_call:


jobs:
  test:
    name: Test and Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter pub get

      - run: flutter test test/unit
